defaultModel: 'openai/gpt-4.1-mini'
style: 'concise'
providers:
  openai:
    apiKey: 'APIKEY' # Replace with your actual OpenAI API key
    url: 'https://' # Optional, defaults to this if omitted
    maxTokens: 100 # Optional, defaults to 100 in openai.js
    models: ['openai/gpt-4.1-mini', 'gpt-3.5-turbo']
  anthropic:
    models: ['claude-3', 'claude-instant']